---
apiVersion: v1
kind: Service
metadata:
    name: website
    namespace: test-ecr-repo
    labels:
        app: website
spec:
    type: LoadBalancer
    selector:
        app: website
    ports:
#     - nodeport: 31479
     - port: 80
       protocol: TCP  
       targetPort: 3000
